alerting:
  github:
    repository-url: "${{ secrets.REPOSITORY }}"
    token: 

endpoints:
  - name: Leantime App
    url: "https://lks-oss-lb-1449847977.us-east-1.elb.amazonaws.com/"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[BODY].status == UP"
      - "[RESPONSE_TIME] < 75"
    alerts:
      - type: github
        failure-threshold: 2
        success-threshold: 3
        send-on-resolved: true
        description: "benerin nih leantime nya bang"

  - name: Gatus App
    url: "localhost:8080"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[BODY].status == UP"
      - "[RESPONSE_TIME] < 75"
    alerts:
      - type: github
        failure-threshold: 2
        success-threshold: 3
        send-on-resolved: true
        description: "benerin nih gatus nya bang"